### ISSUE TITLE
Question: Release plans

### ISSUE THREAD

**Issue by jnape** [i-am-the-slime/purescript-react-testing-library#4]
Hey @i-am-the-slime, do you have any plans for RC (or is it already released and I'm missing something)? This seems to be exactly what I'm looking for, and there don't seem to be many competing solutions for testing react components in purescript.

**Comment by i-am-the-slime** [comment]
Hey @jnape . I am using this today, but by adding it to my spago configuration manually, by adding this to `packages.dhall`:
```
      , react-testing-library =
        { dependencies =
          [ "aff-promise"
          , "console"
          , "debug"
          , "effect"
          , "foreign"
          , "foreign-object"
          , "psci-support"
          , "react-basic-dom"
          , "react-basic-hooks"
          , "remotedata"
          , "run"
          , "simple-json"
          , "spec"
          , "spec-discovery"
          ]
        , repo =
            "https://github.com/i-am-the-slime/purescript-react-testing-library.git"
        , version = "7726ad443ad8c67f94932ab8934640df0ea39fb2"
        }
```
I'll look into releasing this to pursuit now.

**Comment by jnape** [comment]
> I'll look into releasing this to pursuit now.

Nice, that would be wonderful. And thanks for the project!

**Comment by i-am-the-slime** [comment]
@jnape This has a few steps to it, so I'd really advise to use the above workaround until we're settled here. Please let me know how you get on with the library, I'd be very happy to get feedback on how we can improve it.

**Comment by i-am-the-slime** [comment]
Baby steps with: purescript/registry#106.

**Comment by i-am-the-slime** [comment]
Alright, it's out @jnape . 
```
spago upgrade-set && spago install react-testing-library
```

Please reopen if it doesn't work for you.

**Comment by jnape** [comment]
Thank you!
